CSCI-SHU-410-SE-Project/Deskulpt

.github/workflows/build.yaml
.github/workflows/lint-core.yaml
src-tauri/tauri.conf.json

This PR intends to fix errors in the current GitHub action workflows.
```
Invalid workflow file: .github/workflows/lint-core.yaml#L27
The workflow is not valid. .github/workflows/lint-core.yaml (Line: 27, Col: 13): Unexpected symbol: '"ubuntu-20'. Located at position 20 within expression: matrix.platform == "ubuntu-20.04"
```
```
Error You must change the bundle identifier in `tauri.conf.json > tauri > bundle > identifier`. The default value `com.tauri.dev` is not allowed as it must be unique across applications.
```

MAINT Fix GitHub actions setup

---

src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/src/bundler.rs

If one creates a simple widget like this:
```jsx
const React = window.__DESKULPT__.defaultDeps.React;
export default {
render: () => <h1>Welcome!</h1>,
};
```
The bundler removes the `React` assignment because it performs tree shaking by default [[ref](https://rustdoc.swc.rs/src/swc_bundler/bundler/optimize.rs.html#22-33)] and `React` is not explicitly used in the code. However, we require to bring `React` into scope since the (classical) JSX transform  relies on it to transpile.
The workaround is to disabled tree-shaking in the bundler and fold with tree-shaking optimization later by ourselves. This way we can specify `React` as `top_retain` to avoid it from being removed by unused.
Later I will make sure to test this case when the test suite is set up.
/cc …

FIX bundler removing `React` when not explicitly used in code

---

.husky/pre-commit
.lintstagedrc.js

This PR does the following:
- Redirect only when file descriptor 2 (stderr) is connected to the terminal. This workaround is suggested in https://github.com/typicode/husky/issues/968#issuecomment-1184296264. I've tested with the VS Code "commit" button; it raises previously and works now.
- Better escape mechanism in `lint-staged`. This part refers to [the configuration of `next.js`](https://github.com/vercel/next.js/blob/canary/lint-staged.config.js).
@Xinyu-Li-123 Can you please confirm if these solve your issue?

MAINT workaround pre-commit `/dev/tty` not found and fix escape error on Windows CMD

---

src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/src/bundler.rs
src-tauri/src/commands.rs

Fixes #9.
This PR attempts to emit the parsing error in a formatted way instead of panicking (which is clearly wrong). The rendered error message of the reproducer in #9 should now look like this (no color, but formatted):
I've also added a corresponding widget to [`test-widgets`](https://github.com/CSCI-SHU-410-SE-Project/test-widgets/tree/main/err-bundler-parse).
/cc @Xinyu-Li-123 Can you give a review and confirm if this works?

FIX bundler parsing error should not panic

---

src-tauri/Cargo.lock

As is described in the title. Only change one line of Cargo.lock, so I will force merge it.

FIX fix cargo lock, accidentally include version number of normpath when resolving merge conflict

---

src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/src/main.rs
src-tauri/src/setup.rs
src-tauri/tauri.conf.json5

This PR adds a system tray for the application. The system tray currently has two functionalities:
- Left click or click on "Manage": open the manager window.
- Click on "Exit": quit the application.
Other changes include:
- The manager window starts invisible. Use the tray icon to show it.
- Closing the manager window does not really close it. It hides it (setting to invisible) instead.
- The manager window is no longer resizable.

ENH show manager window/close app using system tray

---

.github/workflows/build.yaml
.github/workflows/release.yaml
src-tauri/Cargo.toml
src-tauri/tauri.conf.json

This PR uploads the built binaries of the supported platforms to Github Actions, and automatically generate a comment to either redirect to the location of those artifacts (on success), or to link to the failed workflow (on failure). See https://github.com/CSCI-SHU-410-SE-Project/Deskulpt/pull/58#issuecomment-2110390520 as an example. In particular,
| Success | Failure |
| ------- | ------- |
| ![aae20100a7305e5a55101a13721dfce](https://github.com/CSCI-SHU-410-SE-Project/Deskulpt/assets/108576690/8e8785ee-be1a-41b1-b903-b3e5f01a5b1c) | ![581228b1f548282226683a00e0bc9f5](https://github.com/CSCI-SHU-410-SE-Project/Deskulpt/assets/108576690/45f0c633-d848-46c7-a907-ea8af55663a2) |
I'm also not familiar with it yet; I simply referred to other projects (e.g. …

MAINT better build and release workflows

---

src/manager/App.tsx
src/manager/components/FloatButton.tsx
src/manager/components/ThemeAppearanceToggler.tsx
views/manager.html

See https://github.com/CSCI-SHU-410-SE-Project/Deskulpt/pull/62#pullrequestreview-2112259557 and the following image. There is a margin around the body of the window, and also causes the main contents of the window to be mispositioned. This PR should fix both.
Pinging @ROMEEZHOU for a review to confirm that the problem is fixed on MacOS.

FIX manager layout broken on MacOS

---

.github/dependabot.yaml

Daily schedule is too frequent so this PR switches to weekly update. Besides that, without [grouping](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups) there will be too many PRs open up. Also without specifying [labels](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#labels) default labels will be created which is undesired.
This PR specifies only the `dependencies` label for all such PRs. It also create groups such as `tauri`, `swc`, and `docusaurus`. Also development dependencies are all grouped together. Other production dependencies are still updated individually, though.

MAINT improve dependabot configuration to avoid spam

---

src-tauri/Cargo.lock

Action failure: https://github.com/CSCI-SHU-410-SE-Project/Deskulpt/actions/runs/10442469585/job/28915320334
See https://github.com/rust-lang/rust/issues/125319, the recommended fix is to update the `time` crate to work around the known breakage in type inference.

MAINT update `time` crate to resolve macOS build failure

---

.github/dependabot.yaml

Dependabot seems to fail when `package.json` is in a subdirectory but `pnpm-lock.yaml` is not. See https://github.com/CSCI-SHU-410-SE-Project/Deskulpt/pull/171 for example, where `package.json` is in `/website`, `pnpm-lock.yaml` is in `/`, and the `directory` configuration of the dependabot is set to `/website`. I assume that if the root is `/` it will be able to do the correct update, which is what this PR does. It's perhaps not the best because then website updates will be mixed with main app updates but that's the only thing I can come up with at this moment. Also xref https://github.com/dependabot/dependabot-core/issues/6346.

MAINT fix dependabot failing to update pnpm lockfile in monorepo

---

src/canvas/hooks/useRenderWidgetListener.tsx

Try doing some nonsense in the exported `render` function, e.g.
```js
export default {
render: () => nonExistentObject,
width: "300px",
height: "100px",
};
```
This will in fact fail the render of all widgets and show no error on the canvas. This is because in the current implementation the `render` function is called within the state setter using a updater function, which will be delayed to re-render and thus uncaught. In this PR we call the `render` function in advance to get its returned value so we make sure at least the function itself is correct. Then errors in the returns react component will be caught by the error boundary I believe.

FIX error in the exported render function breaks react render loop

---

.github/workflows/build.yaml

It makes sense to run the comment workflow only for pull requests. This will also fix the workflow that currently always fails on main, e.g. https://github.com/CSCI-SHU-410-SE-Project/Deskulpt/actions/runs/10580517218/job/29316026387

MAINT build comment workflow should not run on push

---

src-tauri/Cargo.lock
src-tauri/Cargo.toml

I cannot remember exactly why `parking_lot` was needed previously (perhaps there's something wrong in the SWC crates e.g. not having a correct dependency tree). But now it seems we no longer need to manually add `parking_lot` - It's pretty clear from the lock file that nothing essentially changes.

DEP remove `parking_lot` from backend dependencies

---

src-tauri/src/bundler/mod.rs
src-tauri/src/testing.rs
src-tauri/tests/fixtures/bundler/default_deps/input/index.js
src-tauri/tests/fixtures/bundler/default_deps/output.js
src-tauri/tests/fixtures/bundler/external_deps/input/index.js
src-tauri/tests/fixtures/bundler/external_deps/output.js
src-tauri/tests/fixtures/bundler/import_url/input/index.jsx
src-tauri/tests/fixtures/bundler/replace_apis/input/index.js
src-tauri/tests/fixtures/bundler/replace_apis/output.js

This PR mainly makes the following changes:
- Removed `external_deps` and converted part of it into `default_deps`. The part specifically for external dependencies will be covered in #66 where the new behavior is implemented.
- Combine `replace_apis` into `default_deps` because `@deskulpt-test/apis` is also a default dependency and the complexity clearly allows to use one test for both of them.
- Skip most error messages in the error chain that does not include useful information, such as `load_transformed failed`.
- Use regex for error messages that include paths, URLs, etc. This is mainly to reduce complexity.
- Improve output of `assert_err_eq` a bit to provide more information of what we actually got

TST remove unnecessary exact checks from bundler tests

---

src-tauri/src/testing.rs

```
warning: duplicated attribute
--> src\testing.rs:1:8
|
1  | #![cfg(test)]
|        ^^^^
|
note: first defined here
--> src/main.rs:26:7
|
26 | #[cfg(test)]
|       ^^^^
help: remove this attribute
--> src\testing.rs:1:8
|
1  | #![cfg(test)]
|        ^^^^
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#duplicated_attributes
= note: `-D clippy::duplicated-attributes` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(clippy::duplicated_attributes)]
```
In `main.rs` we have already introduced the `test` module only when `cfg(test)`. There is no need to declare in addition the `test` module as top-level `cfg(test)`.

MAINT fix linter warning of duplicated attributes

---

src-tauri/src/bundler/common.rs
src-tauri/src/bundler/mod.rs
src-tauri/tests/fixtures/bundler/import_beyond_root/input/index.jsx
src-tauri/tests/fixtures/bundler/import_node_modules/input/index.jsx
src-tauri/tests/fixtures/bundler/import_url/input/index.jsx
src-tauri/tests/fixtures/bundler/strip_types/output.js

Reference: https://github.com/swc-project/swc/blob/f584ef76d75e86da15d0725ac94be35a88a1c946/crates/swc_bundler/tests/common/mod.rs#L90
The main reason is that in newer versions of SWC the bundler seems unable to parse TypeScript syntax directly so it would be better to strip them off early. There's no harm in doing this - it even saves the effort of doing `apply_basic_transforms` everytime after getting the bundled raw module.

MAINT apply TypeScript and React transforms directly in path loader

---

src-tauri/Cargo.toml

This is a very minor change as described in the title.
Probably just making release build a bit faster? But at least this is more *semantically* correct.

MAINT make tauri test feature only dev dependency

---

src-tauri/src/settings.rs

FIX Config file creation may fail if its parent directory (app_config_dir) doesn't exist.

---

.github/dependabot.yaml

We are having far too many noises. It should be okay to group all.
Note that this partially refers to the polars dependabot configuration: https://github.com/pola-rs/polars/blob/main/.github/dependabot.yml

MAINT group all dependabot updates for each type to reduce noises

---

.github/dependabot.yaml

As written in the comment, due to this https://github.com/dependabot/dependabot-core/issues/7501 website group only updates package.json but not pnpm lock in the root since it is not able to detect the root pnpm workspace and pnpm lock files.
The issue has already been stale for over a year and is not likely going to get resolved any time soon. We may want to reorganize the documentation in the future, possibly isolate its dependencies, or even put it into another dedicated repository.

MAINT workaround dependabot issue with pnpm workspace for doc group

---

crates/deskulpt-core/src/states/canvas_click_through.rs
crates/deskulpt-core/src/states/widget_collection.rs
crates/deskulpt-core/src/tray.rs

We should avoid using macros where unnecessary. It will weaken the formatter and editor completion.

refactor: avoid using macro where unnecessary

---

.oxlintrc.json
packages/ui/src/index.ts
src/canvas/hooks/useRemoveWidgetsListener.tsx
src/canvas/hooks/useRenderWidgetListener.tsx
src/manager/App.tsx
src/manager/components/NumberInput.tsx
src/manager/components/SettingToggleShortcut.tsx
src/manager/components/Shortcut.tsx
src/manager/components/WidgetDependencies.tsx
src/manager/hooks/useManagerWidgetStates.ts
src/manager/hooks/useUpdateSettingsListener.ts

`react/jsx-runtime` was a wrong specification. The correct way to do in oxlint is `react` with `react-in-jsx-scope` disabled.

maint: more linter rules especially for react

---

crates/deskulpt-core/Cargo.toml
crates/deskulpt-core/src/commands/open_in_widgets_dir.rs

The `that_detached` is because `that` does not seem to work if I specify another program (I mean, `with_detached` versus `with` in this case), at least on Windows. The detached version does work. Also shell-execute feature is needed.

chore: open detached and with shell-execute on windows

---

crates/deskulpt-core/src/commands/bundle_widget.rs
crates/deskulpt-core/src/commands/exit_app.rs
crates/deskulpt-core/src/commands/open_in_widgets_dir.rs
crates/deskulpt-core/src/commands/rescan_widgets.rs
crates/deskulpt-core/src/path.rs
crates/deskulpt/src/lib.rs

As stated in the title, people can delete e.g. the widgets directory halfway when using the application. That will cause the problem of directory not found. Whenever we access it we should check if it exists and create it if it does not.

refactor: pathext create dir whenever accessed b/c users can delete them halfway

---

Cargo.lock
Cargo.toml
crates/deskulpt-core/Cargo.toml
crates/deskulpt-core/src/commands/call_plugin.rs
crates/deskulpt-core/src/commands/rescan_widgets.rs
crates/deskulpt-core/src/config.rs
crates/deskulpt-plugin-fs/src/commands/append_file.rs
crates/deskulpt-plugin-fs/src/commands/create_dir.rs
crates/deskulpt-plugin-fs/src/commands/exists.rs
crates/deskulpt-plugin-fs/src/commands/is_dir.rs
crates/deskulpt-plugin-fs/src/commands/is_file.rs
crates/deskulpt-plugin-fs/src/commands/read_file.rs
crates/deskulpt-plugin-fs/src/commands/remove_dir.rs
crates/deskulpt-plugin-fs/src/commands/remove_file.rs
crates/deskulpt-plugin-fs/src/commands/write_file.rs
crates/deskulpt-plugin/src/interface.rs
crates/deskulpt-plugin/src/lib.rs
src/manager/components/WidgetContent.tsx
src/manager/components/WidgetContentConfigList.tsx

This is not for security reasons (at least not for now) because uuid v5 is unique as long as namespace is known (which can easily be found from our source code). This is mainly such that users do not use IDs mistakenly (using paths it is too easy for them to know what the ID is).
The reason for choosing uuid v5 is that it is deterministic, so that as long as widget directory did not change, it has the same widget ID. This saves the effort of e.g. comparing paths to identify which widgets are added/removed.

refactor: use uuid v5 instead of dir name as widget id

---

crates/deskulpt-core/src/config.rs

`.to_string` on `anyhow::Error` uses display formatting and does not include the error chain, only the debug formatting does. This is useful for providing more information to users. Instead of just saying e.g. `error in deskulpt.config.json`, it will also mention why, e.g. which field in the JSON is missing or something like that.

enh: include trace in widget configuration errors

---

crates/deskulpt-core/src/events.rs
crates/deskulpt-core/src/settings.rs
crates/deskulpt-plugin-fs/src/commands/append_file.rs
crates/deskulpt-plugin-fs/src/commands/create_dir.rs
crates/deskulpt-plugin-fs/src/commands/exists.rs
crates/deskulpt-plugin-fs/src/commands/is_dir.rs
crates/deskulpt-plugin-fs/src/commands/is_file.rs
crates/deskulpt-plugin-fs/src/commands/read_file.rs
crates/deskulpt-plugin-fs/src/commands/remove_dir.rs
crates/deskulpt-plugin-fs/src/commands/remove_file.rs
crates/deskulpt-plugin-fs/src/commands/write_file.rs

The concensus is: enum variants are SCREAMING_SNAKE_CASE and others are camelCase. On in special cases can this rule be broken, e.g. `Theme` is easier to work with in lowercase (rather than SCREAMING_SNAKE_CASE) because some component libraries take the `theme` prop as `"light" | "dark"`. Note that we put `#[serde(rename_all = "camelCase")]` even in cases where this does not have any effect (i.e., when it is only one word). This is for consistency considerations, and in case if we changed the naming or added more props in the future things automatically works.

chore: serde rename to camel case unless in rare cases

---

crates/deskulpt-core/src/window/mod.rs
src/canvas/index.html
src/manager/index.html
src/vite.config.ts

This is a more intuitive and natural structuring.

chore: move views/x.html to x/index.html

---

crates/deskulpt-core/src/events.rs
crates/deskulpt-core/src/tray.rs
crates/deskulpt-core/src/window/script.rs
crates/deskulpt/src/lib.rs
packages/apis/rollup.config.ts
packages/react/rollup.config.ts
packages/ui/rollup.config.ts
packages/ui/src/jsx-runtime.js

Minor changes. Functionally equivalent.

chore: minor cleanups

---

pnpm-lock.yaml
src/canvas/App.tsx
src/canvas/components/WidgetContainer.tsx
src/canvas/hooks/useRemoveWidgetsListener.tsx
src/canvas/hooks/useRenderWidgetListener.tsx
src/canvas/hooks/useWidgetsStore.ts
src/package.json
src/types/frontend.ts

Alternative to part of #370.
This PR introduces a react state management library [zustand](https://zustand.docs.pmnd.rs/getting-started/introduction) which is the most popular one nowadays. Compared to what we did in #370,
- Widgets do not need to be passed everywhere - it can be obtained from the store.
- We can implement set state functions that achieves the same result as with `useReducer`. But there is also no need to pass the dispatch function everywhere - the functions are standalone and can be directly imported for use.
- Zustand does not restrict to using pure functions, but `useReducer` does, which would require additional `useCallback` to construct non-pure functions on top of the dispatch function. With Zustand this is not necessary.
- We can reduce a lot of typing, since we do …

refactor: use zustand for canvas widgets state management

---

src/canvas/components/ErrorDisplay.tsx
src/canvas/components/WidgetContainer.tsx
src/manager/components/ExternalCopyLink.tsx
src/manager/components/FloatButton.tsx
src/manager/components/ManagerToaster.tsx
src/manager/components/NumberInput.tsx
src/manager/components/SettingToggleShortcut.tsx
src/manager/components/Shortcut.tsx
src/manager/components/ThemeToggler.tsx
src/manager/components/WidgetContent.tsx
src/manager/components/WidgetContentConfigList.tsx
src/manager/components/WidgetContentHeading.tsx
src/manager/components/WidgetContentSettingsList.tsx
src/manager/components/WidgetDependencies.tsx
src/manager/components/WidgetTrigger.tsx
src/manager/tabs/AboutTab.tsx
src/manager/tabs/SettingsTab.tsx
src/manager/tabs/WidgetsTab.tsx

- Props do not need to be exported.
- Components are declared as arrow functions, and then default exported. This will make adding `memo` more elegant.

refactor: style of writing react components

---

src/canvas/App.tsx
src/canvas/components/WidgetContainer.tsx
src/canvas/hooks/useRenderWidgetListener.tsx
src/manager/hooks/useUpdateSettingsListener.ts
src/types/frontend.ts

Similar to part of #370 but improved.
- `App` rerenders only when rescan, which is currently the possibility to add/remove widgets. This is achieved by `useWidgetsStore(useShallow((state) => Object.keys(state.widgets)))`.
- Each `WidgetContainer` rerenders only when its rendering information or settings change, i.e., `WidgetContainer`s do not affect each other. This is achieved by `useWidgetsStore((state) => state.widgets[id])`.
I'm still uncertain about `React.memo` thing, thus not applying it here, but it is something to consider at some point.

perf: avoid unnecessary rerenders on the canvas

---

src/canvas/components/WidgetContainer.tsx

The previous way of rerendering is wrong. We should use `resetKeys`. Currently I only depended on `Component`, because I can't see what other items can cause an error.

fix: correctly reset react error boundary

---

src/canvas/index.html
src/manager/tabs/AboutTab.tsx
src/vite-env.d.ts
src/vite.config.ts

This uses Vite's `define` feature: https://vite.dev/config/shared-options.html#define.

chore: read version from `tauri.conf.json` instead of hardcoding

---

crates/deskulpt-core/src/commands/emit_on_render_ready.rs
crates/deskulpt-core/src/commands/mod.rs
crates/deskulpt-core/src/commands/set_render_ready.rs
crates/deskulpt-core/src/events.rs
crates/deskulpt-core/src/lib.rs
crates/deskulpt-core/src/states/mod.rs
crates/deskulpt-core/src/states/render_ready.rs
crates/deskulpt/src/lib.rs
src/canvas/App.tsx
src/canvas/hooks/useRenderListener.tsx
src/commands.ts
src/events.ts
src/manager/components/WidgetContent.tsx
src/manager/components/WidgetContentSettingsList.tsx
src/manager/hooks/useManagerWidgetStates.ts
src/manager/tabs/WidgetsTab.tsx
src/types/frontend.ts

Previously the manager simply waits for a few seconds before the initial scan and render, because we are unsure whether the canvas is ready to listen to the render event. The case can be summarized as this:
- If the canvas listener is ready first, then everything is okay.
- If the event is emitted before the canvas listener is ready, then the event will be missed.
This PR implements a mechamism that can be summarized as follows:
- The backend keeps a state that records (1) whether the canvas listener is ready and (2) a potentially pending message payload.
- When the canvas listener is ready, mark it in that state, and if there is a pending message payload there immediately emit to the canvas.
- For the manager, instead of just emitting, it calls a backend command that …

feat: better implementation of initial scan and render

---

src/canvas/components/ErrorDisplay.tsx
src/canvas/components/WidgetContainer.tsx
src/canvas/hooks/useWidgetsStore.ts
src/canvas/utils.ts

Simplify the `ErrorDisplay` component. Rename `grabErrorInfo` to `stringifyError`.

chore: minor changes to error display

---

crates/deskulpt-core/src/events.rs
src/canvas/components/ErrorDisplay.tsx
src/canvas/components/WidgetContainer.tsx
src/canvas/hooks/useRenderWidgetsListener.tsx
src/canvas/hooks/useShowToastListener.tsx
src/canvas/hooks/useWidgetsStore.ts
src/canvas/utils.ts
src/types/backend.ts

- Use a `Dialog` modal for the displaying widget error so that it is easier to view.
- Remove JSDoc. Use just normal comments to explain logic. We are already using TypeScript so we do not need JSDoc for type hints, and we are not library to be consumed by people.
- Make `ShowToastPayload` SCREAMING_SNAKE_CASE because it is an enum and it has no good reason to opt-out the rule of SCREAMING_SNAKE_CASE for enum, camelCase for struct.

refactor: better error display and other minor adjustments

---

src/manager/App.tsx
src/manager/components/ThemeToggler.tsx

We can simplify the top-level manager structure by making a list for the tabs. Since it is not declared inside the `App` components, there will be no rerendering issues.
This also fixes the name of `ThemeToggler` which was inconsistent with its filename due to some previous refactoring.

chore: simplify top-level manager structure

---

src/manager/App.tsx
src/manager/components/Widgets/index.tsx

As described in the title, so that there is no need to manually add padding in each tab content to achieve the same result. Also by the way, this decreases the bottom padding of the widgets tab a bit so the space is used more compactly.

chore: add gap between manager top tab triggers and contents

---

src/canvas/components/ErrorDisplay.tsx
src/canvas/components/WidgetContainer.tsx
src/canvas/index.html
src/custom.css
src/manager/App.tsx
src/manager/components/About/index.tsx
src/manager/components/IntegerInput.tsx
src/manager/components/Settings/SectionTable.tsx
src/manager/components/Settings/Shortcut.tsx
src/manager/components/Widgets/Config.tsx
src/manager/components/Widgets/Dependencies.tsx
src/manager/components/Widgets/Settings.tsx
src/manager/components/Widgets/Trigger.tsx
src/manager/components/Widgets/index.tsx
src/manager/index.html

Extracted from and refactored upon #370.
The changes are mostly based on [emotion best practices](https://emotion.sh/docs/best-practices). In particular, *define styles outside of components*, and *use the `style` prop for dynamic styles*.
Another change is to the widget container, which avoid using `zIndex: 9999` but rely on relative stacking context (with an additional wrapper layer) to make sure the handle stays above the component.

refactor: emotion best practices and widget container stacking context

---

crates/deskulpt-core/src/events.rs

With only `#[ts(optional)]` but not `#[serde(skip_serializing_if = "Option::is_none")]`, the optional field will be converted to `null` rather than `undefined` when serializing in backend and deserializing in frontend. This causes the intial render to pass a `null` code despite its declaration being `string | undefined`.

fix: code is null when rendering widgets

---

crates/deskulpt-core/src/commands/bundle_widget.rs
crates/deskulpt-core/src/config.rs
src/bindings.ts
src/manager/components/Widgets/Config.tsx
src/manager/components/Widgets/Dependencies.tsx
src/manager/components/Widgets/Trigger.tsx
src/manager/hooks/useWidgetsStore.ts

- Directly nest `deskulpt_conf and `package_json` in `WidgetConfig`. This can help reduce repetitions as we add more fields.
- The reasons for not adding `#[serde(flatten)]`: specta does not respect this attribute when used in enums; `Option<T>` cannot be marked with flatten.
- Remove `#[serde(content = "content")]` to reduce nesting level.

refactor: widget config construct and serialization

---

.github/workflows/docs.yaml
.gitignore
Cargo.lock
Cargo.toml
crates/deskulpt-core/Cargo.toml
crates/deskulpt-core/src/settings.rs
crates/deskulpt/Cargo.toml
crates/deskulpt/src/main.rs
package.json
src/bindings.ts

Following #500 which pretty prints the settings JSON, this PR is adding `$schema` to help users when they manually edit this file. Though in most cases people should still use app UI for settings this is still an important part of UX as long as we support manual edits.
Generation is done with [schemars](https://docs.rs/schemars/latest/schemars/) and dev-only with a test for generation (same pattern as generating bindings). Schema generation is done in the docs CI and served by vitepress under `/settings-schema.json`.
The command for generating the schema is:
```shell
pnpm build:schema
```
You can find the generated file at `docs/src/public/settings-schema.json`, or you can run `pnpm docs:dev` and go to http://localhost:5173/settings-schema.json. After this PR is merged and the new docs is …

feat: generate settings schema

---

src/manager/components/Widgets/index.tsx

Previously the right half is completely empty and there is no vertical bar there, which looks really strange. Now it looks like the following:

fix: manager ui when there are no widgets

---

.github/actions/setup/action.yaml

Currently the cache keys look like: `v0-rust-Linux-X64-Linux-x64-3bcebdd4-db0c8ef2`, you can see the os and arch are duplicated. This is because the cache action is appending these anyways: https://github.com/Swatinem/rust-cache/blob/14cb63c99f59f3218434d76ea30a71214758bc74/src/config.ts#L77

chore: fix rust cache already appending os and arch to cache key

---

.github/workflows/ci.yaml
.prettierignore
.taplo.toml
package.json
pnpm-lock.yaml

`prettier-toml-plugin` internally uses taplo and all options (at least the ones we need) are supported, so it is a drop-in replacement. And there will not be the path issue with wasm from taplo-cli because it uses the internal `@taplo/lib`. This allows everyone to do toml formatting out of the box instead of having to manually install `taplo-cli` and do `pnpm format:toml` separately.

chore: use prettier-toml-plugin

---

.github/workflows/ci.yaml

It seems that when the `Swatinem/rust-cache@v2` action computes cache key, part of its hash is the environment variables that match the following prefixes `envPrefixes = ["CARGO", "CC", "CFLAGS", "CXX", "CMAKE", "RUST"]`, and `RUST_BACKTRACE` is clearly one of them. Since our cache warmup does not have this environment variable set but our CI workflow does, this will cause the cache to always miss. This PR scopes `RUST_BACKTRACE=1` to only steps that need it (in particular test and rust-based build actions) so that it does not affect the cache key computation step.

fix: scope `RUST_BACKTRACE=1` in ci to avoid affecting cache key computation

---

Cargo.lock
Cargo.toml
crates/deskulpt-build/Cargo.toml
crates/deskulpt-build/README.md
crates/deskulpt-build/src/lib.rs
crates/deskulpt-common/src/bindings.rs
crates/deskulpt-common/src/event.rs
crates/deskulpt-common/src/init.rs
crates/deskulpt-common/src/lib.rs
crates/deskulpt-core/Cargo.toml
crates/deskulpt-core/build.rs
crates/deskulpt-core/src/lib.rs

Towards #533.
Now each plugin never needs to specify their plugin names and their commands/events. They do it only once in the build script:
```rs
fn main() {
deskulpt_build::Builder::default()
.commands(&[
"bundle_widget",
"call_plugin",
"emit_on_render_ready",
"exit_app",
"open_widget",
"rescan_widgets",
"set_render_ready",
"update_settings",
])
.events(&[
"ExitAppEvent",
"RemoveWidgetsEvent",
"RenderWidgetsEvent",
"ShowToastEvent",
"SwitchThemeEvent",
"UpdateSettingsEvent",
])
.build();
}
```
Then in their `lib.rs` they simply need to do:
```rs
// This automatically generates the configure_bindings_builder function
// for use by xtask-gen
deskulpt_common::bindings::configure_bindings_builder!();
pub fn init<R: Runtime>() -> TauriPlugin<R> {
deskulpt_common::init::init_builder!()
// Put …
```

refactor: add deskulpt-build and helper macros to avoid duplicated claration of commands

---

Cargo.lock
Cargo.toml
crates/deskulpt-core/Cargo.toml
crates/deskulpt-core/src/commands/bundle_widget.rs
crates/deskulpt-core/src/commands/call_plugin.rs
crates/deskulpt-core/src/commands/open_widget.rs
crates/deskulpt-core/src/commands/rescan_widgets.rs
crates/deskulpt-core/src/config.rs
crates/deskulpt-core/src/path.rs
crates/deskulpt-core/src/states/widget_config_map.rs
packages/deskulpt/src/bindings.ts
packages/deskulpt/src/manager/components/Widgets/Config.tsx
packages/deskulpt/src/manager/components/Widgets/Dependencies.tsx
packages/deskulpt/src/manager/components/Widgets/Header.tsx
packages/deskulpt/src/manager/components/Widgets/Trigger.tsx
packages/deskulpt/src/manager/hooks/useWidgetsStore.ts

There is no reason to compute a deterministic uuid based on widget directory name as the widget id just to make it not human-readable. By design we can be sure that widget directory names are unique already. Moreover, there are cases where we want them to be human-readable, e.g., editing settings.json file (though this is rare case).

refactor: use widget directory name as widget id

---

.editorconfig
.gitattributes
.github/workflows/cache-warmup.yaml
.github/workflows/ci.yaml

This PR does the following:
- Configure EOL to always use `lf`. I'm not sure if this would work though. The problems are these: (1) on Windows locally running prettier (and some other tools) will cause a bunch of changes (that will go away once staged, but looks messy); (2) though we does not have jobs that will fail on Windows CI currently (because formatting is run on Linux only), this could be a problem if we have such in future.
- Re-group CI into `ci-precheck`, `ci-check`, and `ci-build`:
- `ci-precheck` is run on Linux only and runs formatting, cargo shear, and re-generating auto-generated files. These are fast (relatively) and are platform-independent.
- `ci-check` depends on `ci-precheck` and runs lints and tests. Lints are platform-dependent so it does not fit into precheck. …

ci: add .gitattributes with eol=lf and pipeline ci more reasonably

---

Cargo.toml

As described in the title. Without this, currently the total cache size in one pass is slightly larger than the 10GB limit. Stripping debug symbols should greatly reduce cache size. Note that it would increase the build speed a little bit in local development as well. I don't think there are a lot of cases where we really need full debug info. Even if so, we can specify `RUSTFLAGS="-C debuginfo=2"` when running in those specific debugging cases.

ci: reduce cache size by stripping line-tables-only in debug profile

---

.github/actions/setup-rust/action.yaml
.github/workflows/cache-warmup.yaml
.github/workflows/ci.yaml
.github/workflows/release.yaml

- Do not cache release at all. This saves ~3GB of cache from the 10GB cache limit. Also this means that when our dependencies and crates increase in the future, we get 3x cache size increase rather than 6x.
- In normal PR workflow, disable ci-build completely. Add seperate frontend and backend builds in ci-verify instead. ci-build can still be triggered in PR via `[ci-build]` in commit message, but note that it would have no cache so pretty slow. ci-conclude will not depend on ci-build so that normal PRs can still pass quickly.

ci: completely remove release cache and disable release build in pr workflow

---

crates/xtask-gen/src/bindings.ts.hbs
packages/deskulpt/src/bindings.ts
packages/deskulpt/src/canvas/hooks/useRenderWidgetsListener.tsx
packages/deskulpt/src/manager/components/Widgets/GlobalActions.tsx
packages/deskulpt/src/manager/components/Widgets/Header.tsx
packages/deskulpt/src/manager/hooks/useAppSettingsStore.ts
packages/deskulpt/src/manager/hooks/useExitAppListener.ts
packages/deskulpt/src/manager/hooks/useWidgetsStore.ts

Most of our commands have few arguments that are mostly non-null. This means that specifying named arguments for the command bindings would only add complexity, not reduce. Only in cases where we have a lot of possibly-null arguments would named arguments make things easier, but specta will treat them as null instead of undefined (which makes them still mandatory), and we can always just make a rust-side struct to wrap the arguments anyways.
One benefit of named arguments that still remains is its explicitness, i.e., it is impossible to mess up the order of the arguments. However as said, our current commands have very few arguments in most cases, and we can always make a rust-side struct to wrap the arguments anyways. Even better, if we one day decides to fork specta, we can improve the …

refactor: change command bindings to positional arguments
